РикконсалтингASP/Controllers/AdminPanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using РикконсалтингASP.Models;


namespace РикконсалтингASP.Controllers
{


    public class AdminPanelController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;

        public AdminPanelController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }



        //[Authorize(Roles ="Админ")]
        public async Task<IActionResult> Panel()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                if (userRoles.Contains("Админ"))
                {
                    return View();
                }
                return RedirectToAction("ОшибкаАвторизации", "Ошибки");
            }
            return RedirectToAction("ОшибкаАвторизации", "Ошибки");
        }
    }
}

РикконсалтингASP/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using РикконсалтингASP.Models;
using РикконсалтингASP.ViewModels.ChangeRoleViewModel;
using Microsoft.AspNetCore.Authorization;

namespace РикконсалтингASP.Controllers
{
    
    public class RolesController : Controller
    {

        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
           _userManager = userManager;
        }

      
        [Authorize(Roles = "Админ")]
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }



        [Authorize(Roles = "Админ")]
        public IActionResult Create() => View();



      
        [Authorize(Roles = "Админ")]
        [HttpPost]
        public async Task<IActionResult> Create(string Name)
         {
            if (!string.IsNullOrEmpty(Name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(Name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Start");
                }
                else
                {
                    foreach(var eror in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, eror.Description);
                    }
                }

            }
            return View(Name);


        }

     
        [Authorize(Roles = "Админ")]
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index", "Start");
           
        }




        [Authorize(Roles = "Админ")]
        public IActionResult UserList() => View(_userManager.Users.ToList());



  
        [Authorize(Roles = "Админ")]
        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var AllRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    AllRoles = AllRoles,
                    UserEmail = user.Email,
                    UserId = user.Id,
                    UserRoles = userRoles

                };
                return View(model);
            }

            return NotFound();
        }



        
        [Authorize(Roles = "Админ")]
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }





    }
}

РикконсалтингASP/Controllers/СотрудникController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using РикконсалтингASP.Models;
using РикконсалтингASP.ViewModels.DropdownОргСотр;
using РикконсалтингASP.ViewModels.СотрудникLemel;

namespace РикконсалтингASP.Controllers
{
    [Authorize]
    public class СотрудникController : Controller
    {
        private DbAll dbN;
        private DbAll db;
                
        private DbLemel dbLemels;
        private List<Клиенты> ClienRickCol = new List<Клиенты>();
        private List<Сотрудник> SotrRickCol = new List<Сотрудник>();
        private List<CompanyLemel> ClienLemelData = new List<CompanyLemel>();

        private readonly UserManager<User> _userManager;

        private readonly IHttpContextAccessor _httpContextAccessor;

        public СотрудникController (DbAll context, DbLemel context1, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor)
        {
            
            db = context;
            dbLemels = context1;
            dbN = context;
            _userManager = userManager;
            _httpContextAccessor= httpContextAccessor; /*это для выбора пользователя */

            ClienRickCol =(from x in dbN.Клиент
                          select x).ToList();

            SotrRickCol = (from x in dbN.Сотрудники
                            select x).ToList();



            ClienLemelData = (from x in dbLemels.CompanysLemel          
                              
                              select x).ToList();


           

            _ = ПроверкадвухБазНаИзменение();

        }

        private async Task ПроверкадвухБазНаИзменение()
        {

            //перебираем названия организаций в базе рик и базе лемел
            var Razn = ClienRickCol.Select(x => x.НазвОрг).Except(ClienLemelData.Select(x => x.Название)).ToList();

            if (Razn.Count > 0)
            {
                List<CompanyLemel> ComL = new List<CompanyLemel>();
                //dbLemels.AddRange(Razn);
                //await dbLemels.SaveChangesAsync();
                foreach (var b in Razn)
                {
                    CompanyLemel Cl = new() { Название = b };
                    ComL.Add(Cl);
                }

                await dbLemels.CompanysLemel.AddRangeAsync(ComL);
                await dbLemels.SaveChangesAsync();

            }



            var Sbor = (from x in dbLemels.CompanysLemel
                        join y in dbLemels.СотрудникиLemel on x.Id equals y.CompanyLemelId
                        select new { y, x }).ToList();


            //получение данных текщего пользователя
            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User user = await _userManager.FindByIdAsync(userId);
            var userName = user.UserName;
            /*это для выбора пользователя */




            List<NewUserLemel> LemNew = new List<NewUserLemel>();
            foreach (var b1 in ClienLemelData) /*'перебираем список организаций по названию в базе лемел'*/
            {
                var colSotrOrg = (from x in SotrRickCol
                                  where x.НазвОрганиз == b1.Название
                                  select x).ToList();
                
                if (colSotrOrg.Count > 0)
                {
                    //данные лемелбазы выбираем действующих сотрудников
                    var Colsotrlemel = (from x in Sbor
                                        where x.x.Название == b1.Название
                                        select x.y).ToList();


                    //if (b1.Название == "Юнивест-Групп")
                    //{
                    //    var hj = 0;
                    //}



                    var prom = colSotrOrg.Select(x => x.ФИОСборное).Except(Colsotrlemel.Select(x => x.ФИОСборное)).ToList();
                    
                    if (prom.Count > 0)
                    {
                        
                        foreach (var b in prom)
                        {
                            var UsN = SotrRickCol.Where(x => x.ФИОСборное == b & x.НазвОрганиз == b1.Название).Select(x => x).LastOrDefault();
                            //var usd = _userManager.FindByNameAsync(User.Identity.Name);

                            //CompanyLemel = new CompanyLemel { Название = b1.Название, Id = b1.Id },
                           
                            NewUserLemel newL = new() {
                                ФИОСборное = b,                                
                                IDSotrРик = UsN.КодСотрудники,
                                CompanyLemelId = b1.Id,
                                Пользователь = userName,
                                ДатаИзменения = DateTime.Now,
                                Имя = UsN.Имя,
                                Отчество = UsN.Отчество,
                                Фамилия = UsN.Фамилия,
                                Организация = b1.Название


                            };


                            LemNew.Add(newL);                            
                        }

                       
                    }
                   
                }
                

            }

            if (LemNew.Count > 0)
            {
               dbLemels.СотрудникиLemel.AddRange(LemNew);

               await dbLemels.SaveChangesAsync();
            }


        }
        public JsonResult getEmplbyId(int id)
        {

            //var Nm = name;
            var Nm = (from x in dbLemels.CompanysLemel
                      where x.Id == id
                      select x.Название).FirstOrDefault();

            if (string.IsNullOrEmpty(Nm))
            {
                return Json(null);

            }
           
            List<EmployeDrop> list = new List<EmployeDrop>();
            list = (from x in dbLemels.СотрудникиLemel
                    join y in dbLemels.CompanysLemel on x.CompanyLemelId equals y.Id
                    orderby x.ФИОСборное
                    where y.Название == Nm
                    select new EmployeDrop { ID = x.Id, CompanyDropName = y.Название, Name = x.ФИОСборное }).ToList();

            list.Insert(0, new EmployeDrop { ID = 0, Name = "Выберите сотрудника" });
            return Json(new SelectList(list, "ID", "Name"));
        }
        public async Task<IActionResult> Главная() {

            ViewBag.company =(from x in dbLemels.CompanysLemel
                                     select new CompanyDrop { ID = x.Id, Name = x.Название }).ToList();

             List<CompanyLemel> tyu =await (from x in dbLemels.CompanysLemel
                                       orderby x.Название
                                   select new CompanyLemel { Id = x.Id, Название = x.Название }).ToListAsync();            

            ViewBag.добСотруд = tyu;
            return View();

          
        }
        public ActionResult GetItems(string id)
        {
            return PartialView(db.Сотрудники.Where(c => c.НазвОрганиз == id).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> ДобавитьСотруд()
        {
            ViewBag.company = await (from x in dbLemels.CompanysLemel
                                     select new CompanyDrop { ID = x.Id, Name = x.Название }).ToListAsync();

            //var Model = await(from x in dbLemels.CompanysLemel
            //                       select new CompanyDrop { ID = x.Id, Name = x.Название }).ToListAsync();

            return PartialView("_добавитьСотруд");
        }

        [HttpPost]
        public async Task<IActionResult> AddSotrud(string Фамилия, string Имя, string Отчество, string CompanyDroplist)
        {

            var FIO = (Фамилия + " " + Имя + " " + Отчество).Trim();
            //проверяем есть в базе такой же сотрудник
            //var sotr = await (from x in dbLemels.CompanysLemel
            //                  join y in dbLemels.СотрудникиLemel on x.Id equals y.CompanyLemelId
            //                  where x.Id == int.Parse(CompanyDroplist) && y.ФИОСборное == FIO
            //                  select y).FirstOrDefaultAsync();

            //if (sotr != null)
            //{
            //    string Txt = "Такой сотрудник уже есть в базе!";
            //    return Json(new { name = Txt });
            //}

            //var Org = dbLemels.CompanysLemel.Where(x => x.Id == int.Parse(CompanyDroplist)).Select(x => x.Название).FirstOrDefault();
            ////получение данных текщего пользователя
            //var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            //User user = await _userManager.FindByIdAsync(userId);
            //var userName = user.UserName;
            ///*это для выбора пользователя */



            //var IdOrg = dbLemels.CompanysLemel.Where(x => x.Id == int.Parse(CompanyDroplist)).Select(x => x.Id).FirstOrDefault();
            //NewUserLemel newUserLemel = new NewUserLemel
            //{
            //    CompanyLemelId = IdOrg,
            //    ДатаИзменения = DateTime.Now,
            //    Имя = Имя,
            //    Фамилия = Фамилия,
            //    Отчество = Отчество,
            //    ФИОСборное = FIO,
            //    Организация = Org,
            //    Пользователь = userName
            //};
            //await dbLemels.СотрудникиLemel.AddAsync(newUserLemel);
            //await dbLemels.SaveChangesAsync();

            var tst = "Сотрудник добавлен!";
            return Ok(tst);
        }


       
        public JsonResult AjaxMet(string CompanyDroplist, string FIO)
        {
            //string CompanyDroplist, string FIO

РикконсалтингASP/Views/Shared/_AdPanel.cshtml
@{
    ViewData["Title"] = "_AdPanel";
    Layout = null;
}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/Style.css" rel="stylesheet" />


</head>
<body>
   
    <header>
        <div class="container-fluid">
            <nav class="navbar fixed-top navbar-expand-lg navbar-light rounded" style="background: #f4c430">
                @*fixed-top  box-shadow mb-3*@

                @*<div class="container-fluid">*@
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" asp-area="" asp-controller="Start" asp-action="Index">
                    РикКонсалтинг
                    @*<img src="~/img/logo3.png" alt="">*@
                </a>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                        <li class="nav-item active">
                                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Register">Регистрация пользователя<span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item active">
                                <a class="navbar-brand" asp-area="" asp-controller="Roles" asp-action="Index">Роли <span class="sr-only">(current)</span></a>
                            </li>
                        @*<li class="nav-item active">
                                <a class="navbar-brand" asp-area="" asp-controller="СотрудникиController1" asp-action="AllSotrudnik1">Сотрудники <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#!">Link</a>
                            </li>*@
                    </ul>
                </div>

                              
            </nav>
        </div>

    </header>
   
    <div class="block">
        <div class="container-fluid">            
                <main role="main" class="mt-5">
                    @RenderBody()
                </main>     
         </div>
    </div>

   



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Рикконсалтинг - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>


    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>


@*<style>
        .left {
            background-image: url('~/img/header-slider-bg.png');
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            height: auto;
        }
    </style>*@
</html>

РикконсалтингASP/Views/Shared/_LayView.cshtml
@{
    ViewData["Title"] = "Главная";
}
@*@{
        Layout = null;
    }*@

<!DOCTYPE html>

<html>
<head>
    <title>Главная</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link href="~/css/Style.css" rel="stylesheet" />*@
    @*<link asp-href-include="~/css/**/*.css" />*@

    @*<link href="~/css/StyleSidebar.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="~/css/StyleSidebar.css" asp-append-version="true" />
    @*<link href="~css\bootstrap.min.css" rel="stylesheet" />*@
    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>*@

    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>

    <div class="container-fluid">
        <div class="wrapper">
            <div class="sidebar">
                <h2>Меню</h2>
                <ul>
                    <li><a href="#"><i class="fas fa-home"></i>Home</a></li>
                    <li><a href="#"><i class="fas fa-user"></i>Profile</a></li>
                    <li><a href="#"><i class="fas fa-address-card"></i>About</a></li>
                    <li><a href="#"><i class="fas fa-project-diagram"></i>portfolio</a></li>



                    <li>

                        <a asp-controller="Сотрудник" asp-action="Главная"><i class="fas fa-blog"></i>Сотрудники</a>

                        @*<select id="selectId">
                                <option value="">Сотрудники</option>
                                <option value="">Добавить сотрудника</option>
                            </select>*@



                    </li>



                    <li><a asp-controller="AdminPanel" asp-action="Panel"><i class="fas fa-user-lock"></i>Админ панель</a></li>
                    <li><a asp-controller="Account" asp-action="Logout1"><i class="fas fa-door-open"></i>Выйти</a></li>
                    <li><a asp-controller="СотрудникиController1" asp-action="AllSotrudnik1"><i class="fas fa-address-book"></i>Сотрудники</a></li>
                </ul>
                @*<div class="social_media">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>*@
            </div>


            <div class="main_content">
                
                <div class="header">@User.Identity.Name</div>

                <div class="info">

                    @RenderBody()

                    @*@RenderSection("Scripts", required: false)*@

                </div>
            </div>

        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Рикконсалтинг - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>


    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/8709e3c1f3.js" crossorigin="anonymous"></script>
    @*<script src="~\js\bootstrap.min.js"></script>*@

    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="https://getbootstrap.com/docs/3.4/assets/js/vendor/holder.min.js"></script>


</body>
</html>

РикконсалтингASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@*@model РикконсалтингASP.ViewModels.Register.LoginViewModel*@
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/Style.css" rel="stylesheet" />


</head>
<body>
    @*<img src="~/img/header-slider-bg.png" alt="" />*@
    <header>
        <div class="container-fluid">
            <nav class="navbar fixed-top navbar-expand-lg navbar-light rounded" style="background: #f4c430">
                @*fixed-top  box-shadow mb-3*@

                @*<div class="container-fluid">*@
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" asp-area="" asp-controller="Start" asp-action="Index">
                        РикКонсалтинг
                        @*<img src="~/img/logo3.png" alt="">*@
                    </a>

                    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                        @*<ul class="navbar-nav mr-auto mt-2 mt-md-0">
                            <li class="nav-item active">
                            <a class="navbar-brand" asp-area="" asp-controller="Сотрудник" asp-action="Главная">Сотр <span class="sr-only">(current)</span></a>
                        </li>*@
                        @*<li class="nav-item active">
                            <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">Вход <span class="sr-only">(current)</span></a>
                        </li>*@
                            @*<li class="nav-item active">
                                <a class="navbar-brand" asp-area="" asp-controller="СотрудникиController1" asp-action="AllSotrudnik1">Сотрудники <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#!">Link</a>
                            </li>*@
                        </ul>
                    </div>

                    <div class="nav navbar-nav navbar-toggler-right" id="navbarTogglerDemo02">
                        @*ml-auto mr-lg-2*@

                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="row">

                                <div class="col-md-8">
                                    <p class="help-block">@User.Identity.Name</p>
                                </div>
                                @*text-lg-right"*@
                                <div class="col-md-4">
                                    <form method="post" asp-controller="Account" asp-action="Logout">
                                        <input type="submit" class="btn-info" value="Выход" />
                                    </form>
                                </div>


                            </div>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Login" asp-ant>Вход</a>
                            @*<p>/</p>
                        <a asp-controller="Account" asp-action="Register">Регистрация</a>*@
                        }
                    </div>



                @*</div>*@
            </nav>
        </div>

    </header>
    @*<img src="~/img/header-slider-bg.png" alt="" />*@
    <div class="block">
        <div class="container-fluid">
            @if (User.Identity.IsAuthenticated)
            {
                <main role="main" @*class="mt-5"*@>
                    @RenderBody()
                </main>
            }
            else
            {
                <main role="main" class="mt-5">
                    @RenderBody()
                </main>
            }


        </div>
    </div>

    @*<div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")  Menu - это IAction. Nav - это контроллер
        </div>*@




    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Рикконсалтинг - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>


    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)    
</body>


@*<style>
        .left {
            background-image: url('~/img/header-slider-bg.png');
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            height: auto;
        }
    </style>*@
</html>